name: pomodoro
description: A pomodoro timer intended for Twitch streams.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_colorpicker: ^1.0.3
  just_audio: ^0.9.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

 
  assets:
    - assets/audio/heylisten.mp3
    - assets/audio/finished.mp3
